### PR TITLE
"Added `withCredentials` which fixes #6"

### LINKED ISSUE #6: withCredentials not being set on XHR
Hi! I just noticed in the fallback case `xhr.withCredentials` is not being set, and specifically its not being set to true.

From all my testing `navigator.sendBeacon` is sending through the cookies on the domain, so to make this behaviour more consistent shouldn't the XHR fallback also send the cookies through?

### PR DESCRIPTION
**Pull request by tylerkrett**
Added fix for #6

### CODE REVIEW

**Comment by miguelmota** [comment]
thanks @tylerkrett

**Comment by Wildhoney** [comment]
Could you please `npm publish` `v0.0.5` @miguelmota?

```bash
matilda-pro:resdev atimberlake$ npm info navigator.sendbeacon
 
{ name: 'navigator.sendbeacon',
  description: 'Polyfill for navigator.sendBeacon()',
  'dist-tags': { latest: '0.0.3' },
  versions: [ '0.0.1', '0.0.2', '0.0.3' ]

// ...
```

**Comment by miguelmota** [comment]
already published @Wildhoney 

```js
{ name: 'navigator.sendbeacon',
  description: 'Polyfill for navigator.sendBeacon()',
  'dist-tags': { latest: '0.0.5' },
  versions: [ '0.0.1', '0.0.2', '0.0.3', '0.0.4', '0.0.5' ],
  maintainers: [ 'miguelmota <hello@miguelmota.com>' ],
  time:
   { modified: '2017-03-24T19:04:10.768Z',
     created: '2015-04-22T05:03:45.263Z',
     '0.0.1': '2015-04-22T05:03:45.263Z',
     '0.0.2': '2015-04-22T05:05:51.065Z',
     '0.0.3': '2016-03-13T02:21:55.363Z',
     '0.0.4': '2017-03-24T18:35:27.747Z',
     '0.0.5': '2017-03-24T19:04:10.768Z' },
  homepage: 'https://github.com/miguelmota/Navigator.sendBeacon',
  keywords: [ 'navigator', 'beacon', 'polyfill' ],
  repository:
   { type: 'git',
miguelmota/Navigator.sendBeacon.git' },
  author: 'Miguel Mota <hello@miguelmota.com> (http://www.miguelmota.com/)',
  bugs: { url: 'https://github.com/miguelmota/Navigator.sendBeacon/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '0.0.5',
  main: 'sendbeacon.js',
  directories: { test: 'test' },
  scripts: { test: 'tape test/*.js' },
  devDependencies: { tape: '^3.0.3' },
  gitHead: 'faa8788ce1b15bd477cff98530b9f1a6dd7473b3',
  dist:
   { shasum: 'ac60fa8523c08680fdae0f3b91ebae2c789f8bde',
 ```

**Comment by Wildhoney** [comment]
Thanks @miguelmota oddly after `npm cache clean` it gave me the correct list of versions.

**Pull request merged**
